apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: external-ca-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
    serviceDomain: cluster.local
  controlPlaneEndpoint:
    host: external-ca-cluster-lb
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: external-ca-controlplane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: external-ca-cluster
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: external-ca-cluster
  namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: external-ca-controlplane
  namespace: default
spec:
  replicas: 1
  version: v1.29.2
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: external-ca-controlplane
      namespace: default
  kubeadmConfigSpec:
    externalCA: true
    preKubeadmCommands:
    - mkdir -p /etc/kubernetes/pki/etcd
    files:
    - path: /etc/kubernetes/pki/ca.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-ca-crt
    - path: /etc/kubernetes/pki/front-proxy-ca.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-front-proxy-ca-crt
    - path: /etc/kubernetes/pki/etcd/ca.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-ca-crt
    - path: /etc/kubernetes/pki/sa.pub
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-sa-pub
    - path: /etc/kubernetes/pki/sa.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-sa-key
    - path: /etc/kubernetes/pki/apiserver.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-apiserver-crt
    - path: /etc/kubernetes/pki/apiserver.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-apiserver-key
    - path: /etc/kubernetes/pki/apiserver-kubelet-client.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-apiserver-kubelet-client-crt
    - path: /etc/kubernetes/pki/apiserver-kubelet-client.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-apiserver-kubelet-client-key
    - path: /etc/kubernetes/pki/front-proxy-client.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-front-proxy-client-crt
    - path: /etc/kubernetes/pki/front-proxy-client.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-front-proxy-client-key
    - path: /etc/kubernetes/pki/apiserver-etcd-client.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-apiserver-etcd-client-crt
    - path: /etc/kubernetes/pki/apiserver-etcd-client.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-apiserver-etcd-client-key
    - path: /etc/kubernetes/pki/etcd/server.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-server-crt
    - path: /etc/kubernetes/pki/etcd/server.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-server-key
    - path: /etc/kubernetes/pki/etcd/peer.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-peer-crt
    - path: /etc/kubernetes/pki/etcd/peer.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-peer-key
    - path: /etc/kubernetes/pki/etcd/healthcheck-client.crt
      owner: root:root
      permissions: "0644"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-healthcheck-client-crt
    - path: /etc/kubernetes/pki/etcd/healthcheck-client.key
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: pki-etcd-healthcheck-client-key
    - path: /etc/kubernetes/admin.conf
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: kubeconfig-admin
    - path: /etc/kubernetes/kubelet.conf
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: kubeconfig-kubelet
    - path: /etc/kubernetes/super-admin.conf
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: kubeconfig-super-admin
    - path: /etc/kubernetes/controller-manager.conf
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: kubeconfig-controller-manager
    - path: /etc/kubernetes/scheduler.conf
      owner: root:root
      permissions: "0600"
      contentFrom:
        secret:
          name: external-ca-cluster-external-ca-files
          key: kubeconfig-scheduler
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
    initConfiguration:
      skipPhases:
      - kubelet-finalize/experimental-cert-rotation
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: external-ca-controlplane
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: external-ca-worker-md-0
  namespace: default
spec:
  clusterName: external-ca-cluster
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: external-ca-cluster
  template:
    spec:
      clusterName: external-ca-cluster
      version: v1.29.2
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: external-ca-worker
          namespace: default
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: external-ca-worker
        namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: external-ca-worker
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: external-ca-worker
  namespace: default
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: kubeconfig-kubelet
            name: external-ca-cluster-external-ca-files
        owner: root:root
        path: /etc/kubernetes/kubelet.conf
        permissions: "0600"
      - contentFrom:
          secret:
            key: pki-ca-crt
            name: external-ca-cluster-external-ca-files
        owner: root:root
        path: /etc/kubernetes/pki/ca.crt
        permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          ignorePreflightErrors:
          - FileAvailable--etc-kubernetes-kubelet.conf
          - FileAvailable--etc-kubernetes-pki-ca.crt
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
