apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: __CLUSTER_NAME__
  namespace: __NAMESPACE__
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
    serviceDomain: cluster.local
__CONTROL_PLANE_ENDPOINT_BLOCK__
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: __KCP_NAME__
    namespace: __NAMESPACE__
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: __CLUSTER_NAME__
    namespace: __NAMESPACE__
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: __CLUSTER_NAME__
  namespace: __NAMESPACE__
